name: Apply Terraform 
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

on: push
jobs: 
  plan:
      runs-on: ubuntu-latest 
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform Install 
          run: terraform init -input=false

        - name: Terraform init
          run: terraform init -input=false
        - name: Appl terraform 
          run: terraform apply -auto-approve -input=false
