name: Apply Terraform 
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}


on: push
jobs: 
  plan:
      runs-on: ubuntu-latest 
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform Install 
          run: terraform init -input=false

        - name: Terraform init
          run: terraform init -input=false
        - name: Appl terraform 
          run: terraform apply -auto-approve -input=false
  deploy:
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: eu-west-2
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and Push 
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: REPOSITORY
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG    
